export const coffees = [
  {
    id: 1,
    types: ["TRADICIONAL"],
    title: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    image: "/coffees/tradicional.png",
    price: 9.9,
    amount: 0,
  },
  {
    id: 2,
    types: ["TRADICIONAL"],
    title: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    image: "/coffees/americano.png",
    price: 15.9,
    amount: 0,
  },
  {
    id: 3,
    types: ["TRADICIONAL"],
    title: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    image: "/coffees/cremoso.png",
    price: 12.9,
    amount: 0,
  },
  {
    id: 4,
    types: ["TRADICIONAL", "GELADO"],
    title: "Expresso Gelado",
    description: "Bebida preparada com café expresso batido com gelo",
    image: "/coffees/gelado.png",
    price: 5.9,
    amount: 0,
  },
  {
    id: 5,
    types: ["TRADICIONAL", "COM LEITE"],
    title: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    image: "/coffees/leite.png",
    price: 11.9,
    amount: 0,
  },
  {
    id: 6,
    types: ["TRADICIONAL", "COM LEITE"],
    title: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    image: "/coffees/latte.png",
    price: 9.9,
    amount: 0,
  },
  {
    id: 7,
    types: ["TRADICIONAL", "COM LEITE"],
    title: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    image: "/coffees/capuccino.png",
    price: 10.9,
    amount: 0,
  },
  {
    id: 8,
    types: ["TRADICIONAL", "COM LEITE"],
    title: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    image: "/coffees/macchiato.png",
    price: 15.9,
    amount: 0,
  },
  {
    id: 9,
    types: ["TRADICIONAL", "COM LEITE"],
    title: "Mocaccino",
    description: "Café expresso com calda de chocolate, leite e espuma",
    image: "/coffees/mocaccino.png",
    price: 7.9,
    amount: 0,
  },
  {
    id: 10,
    types: ["ESPECIAL", "COM LEITE"],
    title: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    image: "/coffees/chocolate.png",
    price: 12.9,
    amount: 0,
  },
  {
    id: 11,
    types: ["ESPECIAL", "ALCOÓLICO", "GELADO"],
    title: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    image: "/coffees/cubano.png",
    price: 9.9,
    amount: 0,
  },
  {
    id: 12,
    types: ["ESPECIAL"],
    title: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    image: "/coffees/havaiano.png",
    price: 20.9,
    amount: 0,
  },
  {
    id: 13,
    types: ["ESPECIAL"],
    title: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    image: "/coffees/arabe.png",
    price: 9.9,
    amount: 0,
  },
  {
    id: 14,
    types: ["ESPECIAL", "ALCOÓLICO"],
    title: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    image: "/coffees/irlandes.png",
    price: 10.9,
    amount: 0,
  },
];

// export const coffees = [
//   {
//     id: 1,
//     types: ["TRADICIONAL"],
//     title: "Expresso Tradicional",
//     description: "O tradicional café feito com água quente e grãos moídos",
//     price: 9.9,
//     amount: 0,
//   },
//   {
//     id: 2,
//     types: ["TRADICIONAL"],
//     title: "Expresso Americano",
//     description: "Expresso diluído, menos intenso que o tradicional",
//     price: 15.9,
//     amount: 0,
//   },
//   {
//     id: 3,
//     types: ["TRADICIONAL"],
//     title: "Expresso Cremoso",
//     description: "Café expresso tradicional com espuma cremosa",
//     price: 12.9,
//     amount: 0,
//   },
//   {
//     id: 4,
//     types: ["TRADICIONAL", "GELADO"],
//     title: "Expresso Gelado",
//     description: "Bebida preparada com café expresso batido com gelo",
//     price: 5.9,
//     amount: 0,
//   },
//   {
//     id: 5,
//     types: ["TRADICIONAL", "COM LEITE"],
//     title: "Café com Leite",
//     description: "Meio a meio de expresso tradicional com leite vaporizado",
//     price: 11.9,
//     amount: 0,
//   },
//   {
//     id: 6,
//     types: ["TRADICIONAL", "COM LEITE"],
//     title: "Latte",
//     description:
//       "Uma dose de café expresso com o dobro de leite e espuma cremosa",
//     price: 9.9,
//     amount: 0,
//   },
//   {
//     id: 7,
//     types: ["TRADICIONAL", "COM LEITE"],
//     title: "Capuccino",
//     description:
//       "Bebida com canela feita de doses iguais de café, leite e espuma",
//     price: 10.9,
//     amount: 0,
//   },
//   {
//     id: 8,
//     types: ["TRADICIONAL", "COM LEITE"],
//     title: "Macchiato",
//     description:
//       "Café expresso misturado com um pouco de leite quente e espuma",
//     price: 15.9,
//     amount: 0,
//   },
//   {
//     id: 9,
//     types: ["TRADICIONAL", "COM LEITE"],
//     title: "Mocaccino",
//     description: "Café expresso com calda de chocolate, leite e espuma",
//     price: 7.9,
//     amount: 0,
//   },
//   {
//     id: 10,
//     types: ["ESPECIAL", "COM LEITE"],
//     title: "Chocolate Quente",
//     description: "Bebida feita com chocolate dissolvido no leite quente e café",
//     price: 12.9,
//     amount: 0,
//   },
//   {
//     id: 11,
//     types: ["ESPECIAL", "ALCOÓLICO", "GELADO"],
//     title: "Cubano",
//     description:
//       "Drink gelado de café expresso com rum, creme de leite e hortelã",
//     price: 9.9,
//     amount: 0,
//   },
//   {
//     id: 12,
//     types: ["ESPECIAL"],
//     title: "Havaiano",
//     description: "Bebida adocicada preparada com café e leite de coco",
//     price: 20.9,
//     amount: 0,
//   },
//   {
//     id: 13,
//     types: ["ESPECIAL"],
//     title: "Árabe",
//     description: "Bebida preparada com grãos de café árabe e especiarias",
//     price: 9.9,
//     amount: 0,
//   },
//   {
//     id: 14,
//     types: ["ESPECIAL", "ALCOÓLICO"],
//     title: "Irlandês",
//     description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
//     price: 10.9,
//     amount: 0,
//   },
// ];
